## 
## Boneyard

# png(filename=paste0(plot.path,"PLSF_GAM_weekly_P.png"),width=12,height=8,units="in",res=200,type="windows",bg="white")
par(family="serif",mar=c(2,2.5,1,1.5),oma=c(1,1,1.5,0.25));
layout(matrix(1:30,5,6,byrow = T))

yaxs.cex=0.8
labs.cex=0.9
inflow.col=viridisLite::viridis(4,alpha=0.5,option="E")[2]
outflow.col=viridisLite::viridis(4,alpha=0.5,option="E")[3]

# TP
{
  ylim.val=c(-2,3);by.y=2;ymaj=seq(ylim.val[1],ylim.val[2],by.y);ymin=seq(ylim.val[1],ylim.val[2],by.y/2)
  xlim.val=c(0,366);by.x=90;xmaj=seq(xlim.val[1],xlim.val[2],by.x);xmin=seq(xlim.val[1],xlim.val[2],by.x/3)
  plot(fit~DOY,TP.in.DOY.sig,ylim=ylim.val,xlim=xlim.val,ann=F,axes=F,type="n")
  abline(h=ymaj,v=xmaj,lty=3,col="grey")
  abline(h=0)
  points(m.TP.in$model$DOY,partial.resids.TP.in[,1],pch=19,col=inflow.col)
  lines(fit~DOY,TP.in.DOY.sig,lwd=2)
  lines(UCI ~ DOY, data = TP.in.DOY.sig, lty = "dashed")
  lines(LCI ~ DOY, data = TP.in.DOY.sig, lty = "dashed")
  # lines(dsig.incr ~ DOY, data = TP.in.DOY.sig, col = "red", lwd = 3,lty=1)
  # lines(dsig.decre ~ DOY, data = TP.in.DOY.sig, col = "blue", lwd = 3,lty=1)
  axis_fun(1,xmaj,xmin,xmaj,line=-0.5,cex=yaxs.cex);
  axis_fun(2,ymaj,ymin,format(ymaj),cex=yaxs.cex);box(lwd=1)
  mtext(side=3,adj=0,"s(DOY)",cex=labs.cex)
  # mtext(side=1,line=2,"DOY",cex=labs.cex)
  mtext(side=2,line=1.5,"Effect",cex=labs.cex)
  
  ylim.val=c(-2,4);by.y=2;ymaj=seq(ylim.val[1],ylim.val[2],by.y);ymin=seq(ylim.val[1],ylim.val[2],by.y/2)
  xlim.val=c(2010,2020);by.x=5;xmaj=seq(xlim.val[1],xlim.val[2],by.x);xmin=seq(xlim.val[1],xlim.val[2],by.x/by.x)
  plot(fit.CY~CY,TP.in.pdat,ylim=ylim.val,xlim=xlim.val,ann=F,axes=F,type="n")
  abline(h=ymaj,v=xmaj,lty=3,col="grey")
  abline(h=0)
  points(m.TP.in$model$CY,partial.resids.TP.in[,2],pch=19,col=inflow.col)
  lines(fit.CY~CY,TP.in.pdat,lwd=2)
  lines(upper.CY ~ CY, data = TP.in.pdat, lty = "dashed")
  lines(lower.CY ~ CY, data = TP.in.pdat, lty = "dashed")
  # lines(dsig.CY.incr ~ CY, data = TP.in.pdat, col = "red", lwd = 3,lty=1)
  # lines(dsig.CY.decr ~ CY, data = TP.in.pdat, col = "blue", lwd = 3,lty=1)
  axis_fun(1,xmaj,xmin,xmaj,line=-0.5,cex=yaxs.cex);
  axis_fun(2,ymaj,ymin,format(ymaj),cex=yaxs.cex);box(lwd=1)
  mtext(side=3,adj=0,"s(Year)",cex=labs.cex)
  # mtext(side=1,line=2,"Year",cex=labs.cex)
  mtext(side=3,line=1,"Inflow",cex=1,font=2)
  mtext(side=2,line=1.5,"Effect",cex=labs.cex)
  
  ylim.val=c(5,1000);ymaj=log.scale.fun(ylim.val,"major");ymin=log.scale.fun(ylim.val,"minor");#by.y=500;ymaj=seq(ylim.val[1],ylim.val[2],by.y);ymin=seq(ylim.val[1],ylim.val[2],by.y/2)
  xlim.val=date.fun(c("2008-12-01","2020-12-31"));xmaj=seq(xlim.val[1],xlim.val[2],"5 years");xmin=seq(xlim.val[1],xlim.val[2],"1 years")
  plot(TP.ugL~Date,dat.in,ylim=ylim.val,xlim=xlim.val,ann=F,axes=F,type="n",yaxs="i",log="y")
  abline(h=ymaj,v=xmaj,lty=3,col="grey")
  with(dat.in,pt_line(Date,TP.ugL,2,inflow.col,1,21,adjustcolor(inflow.col,0.2),cex=0.75,pt.col=inflow.col))
  trend=mblm::mblm(value~CY.d,subset(wq.dat.melt,Site=="Godbout"&variable=="TP.ugL"))
  x.val=with(subset(wq.dat.melt,Site=="Godbout"&variable=="TP.ugL"),seq(min(CY.d),max(CY.d),length.out=15))
  fit=predict(trend,newdata=data.frame(CY.d=x.val))
  lines(date.fun(lubridate::date_decimal(x.val)),fit,lwd=2)
  with(subset(pt.trend.all,Site=="Godbout"&param=="TP.ugL"),abline(v=date.change2,col="red",lty=2))
  axis_fun(1,xmaj,xmin,format(xmaj,"%Y"),line=-0.5,cex=yaxs.cex);
  axis_fun(2,ymaj,ymin,format(round(ymaj/1000,2),digits=2),cex=yaxs.cex);box(lwd=1)
  # mtext(side=1,line=2,"Date",cex=labs.cex)
  mtext(side=2,line=2.5,"TP (mg L\u207B\u00B9)",cex=labs.cex)
  mtext(side=3,adj=0,"Conc.",cex=labs.cex)
  
  ylim.val=c(-2,3);by.y=2;ymaj=seq(ylim.val[1],ylim.val[2],by.y);ymin=seq(ylim.val[1],ylim.val[2],by.y/2)
  xlim.val=c(0,366);by.x=90;xmaj=seq(xlim.val[1],xlim.val[2],by.x);xmin=seq(xlim.val[1],xlim.val[2],by.x/3)
  plot(fit~DOY,TP.out.DOY.sig,ylim=ylim.val,xlim=xlim.val,ann=F,axes=F,type="n")
  abline(h=ymaj,v=xmaj,lty=3,col="grey")
  abline(h=0)
  points(m.TP.out$model$DOY,partial.resids.TP.out[,1],pch=19,col=outflow.col)
  lines(fit~DOY,TP.out.DOY.sig,lwd=2)
  lines(UCI ~ DOY, data = TP.out.DOY.sig, lty = "dashed")
  lines(LCI ~ DOY, data = TP.out.DOY.sig, lty = "dashed")
  lines(dsig.incr ~ DOY, data = TP.out.DOY.sig, col = "red", lwd = 3,lty=1)
  lines(dsig.decre ~ DOY, data = TP.out.DOY.sig, col = "blue", lwd = 3,lty=1)
  axis_fun(1,xmaj,xmin,xmaj,line=-0.5,cex=yaxs.cex);
  axis_fun(2,ymaj,ymin,format(ymaj),cex=yaxs.cex);box(lwd=1)
  mtext(side=3,adj=0,"s(DOY)",cex=labs.cex)
  # mtext(side=1,line=2,"DOY",cex=labs.cex)
  mtext(side=2,line=1.5,"Effect",cex=labs.cex)
  
  ylim.val=c(-2,2);by.y=2;ymaj=seq(ylim.val[1],ylim.val[2],by.y);ymin=seq(ylim.val[1],ylim.val[2],by.y/2)
  xlim.val=c(2010,2020);by.x=5;xmaj=seq(xlim.val[1],xlim.val[2],by.x);xmin=seq(xlim.val[1],xlim.val[2],by.x/by.x)
  plot(fit.CY~CY,TP.out.pdat,ylim=ylim.val,xlim=xlim.val,ann=F,axes=F,type="n")
  abline(h=ymaj,v=xmaj,lty=3,col="grey")
  abline(h=0)
  points(m.TP.out$model$CY,partial.resids.TP.out[,2],pch=19,col=outflow.col)
  lines(fit.CY~CY,TP.out.pdat,lwd=2)
  lines(upper.CY ~ CY, data = TP.out.pdat, lty = "dashed")
  lines(lower.CY ~ CY, data = TP.out.pdat, lty = "dashed")
  lines(dsig.CY.incr ~ CY, data = TP.out.pdat, col = "red", lwd = 3,lty=1)
  lines(dsig.CY.decr ~ CY, data = TP.out.pdat, col = "blue", lwd = 3,lty=1)
  axis_fun(1,xmaj,xmin,xmaj,line=-0.5,cex=yaxs.cex);
  axis_fun(2,ymaj,ymin,format(ymaj),cex=yaxs.cex);box(lwd=1)
  mtext(side=3,adj=0,"s(Year)",cex=labs.cex)
  # mtext(side=1,line=2,"Year",cex=labs.cex)
  mtext(side=3,line=1,"Outflow",cex=1,font=2)
  mtext(side=2,line=1.5,"Effect",cex=labs.cex)
  
  ylim.val=c(5,1000);ymaj=log.scale.fun(ylim.val,"major");ymin=log.scale.fun(ylim.val,"minor");#by.y=500;ymaj=seq(ylim.val[1],ylim.val[2],by.y);ymin=seq(ylim.val[1],ylim.val[2],by.y/2)
  xlim.val=date.fun(c("2008-12-01","2020-12-31"));xmaj=seq(xlim.val[1],xlim.val[2],"5 years");xmin=seq(xlim.val[1],xlim.val[2],"1 years")
  plot(TP.ugL~Date,dat.in,ylim=ylim.val,xlim=xlim.val,ann=F,axes=F,type="n",yaxs="i",log="y")
  abline(h=ymaj,v=xmaj,lty=3,col="grey")
  with(dat.in,pt_line(Date,TP.ugL,2,outflow.col,1,21,outflow.col,cex=0.75,pt.col=outflow.col))
  trend=mblm::mblm(value~CY.d,subset(wq.dat.melt,Site=="Godbout"&variable=="TP.ugL"))
  x.val=with(subset(dat.in,is.na(TP.ugL)==F),seq(min(CY.d),max(CY.d),length.out=15))
  fit=predict(trend,newdata=data.frame(CY.d=x.val))
  lines(date.fun(lubridate::date_decimal(x.val)),fit,lwd=2)
  with(subset(pt.trend.all,Site=="Lake_Outlet"&param=="TP.ugL"),abline(v=date.fun(lubridate::date_decimal(date.change)),col="red",lty=2))
  axis_fun(1,xmaj,xmin,format(xmaj,"%Y"),line=-0.5,cex=yaxs.cex);
  axis_fun(2,ymaj,ymin,format(round(ymaj/1000,2),digits=2),cex=yaxs.cex);box(lwd=1)
  # mtext(side=1,line=2,"Date",cex=labs.cex)
  mtext(side=2,line=2.5,"TP (mg L\u207B\u00B9)",cex=labs.cex)
  mtext(side=3,adj=0,"Conc.",cex=labs.cex)
}

# DP
{
  ylim.val=c(-2,3);by.y=2;ymaj=seq(ylim.val[1],ylim.val[2],by.y);ymin=seq(ylim.val[1],ylim.val[2],by.y/2)
  xlim.val=c(0,366);by.x=90;xmaj=seq(xlim.val[1],xlim.val[2],by.x);xmin=seq(xlim.val[1],xlim.val[2],by.x/3)
  plot(fit~DOY,DP.in.DOY.sig,ylim=ylim.val,xlim=xlim.val,ann=F,axes=F,type="n")
  abline(h=ymaj,v=xmaj,lty=3,col="grey")
  abline(h=0)
  points(m.DP.in$model$DOY,partial.resids.DP.in[,1],pch=19,col=inflow.col)
  lines(fit~DOY,DP.in.DOY.sig,lwd=2)
  lines(UCI ~ DOY, data = DP.in.DOY.sig, lty = "dashed")
  lines(LCI ~ DOY, data = DP.in.DOY.sig, lty = "dashed")
  lines(dsig.incr ~ DOY, data = DP.in.DOY.sig, col = "red", lwd = 3,lty=1)
  lines(dsig.decre ~ DOY, data = DP.in.DOY.sig, col = "blue", lwd = 3,lty=1)
  axis_fun(1,xmaj,xmin,xmaj,line=-0.5,cex=yaxs.cex);
  axis_fun(2,ymaj,ymin,format(ymaj),cex=yaxs.cex);box(lwd=1)
  mtext(side=3,adj=0,"s(DOY)",cex=labs.cex)
  # mtext(side=1,line=2,"DOY",cex=labs.cex)
  mtext(side=2,line=1.5,"Effect",cex=labs.cex)
  
  ylim.val=c(-2,3);by.y=2;ymaj=seq(ylim.val[1],ylim.val[2],by.y);ymin=seq(ylim.val[1],ylim.val[2],by.y/2)
  xlim.val=c(2010,2020);by.x=5;xmaj=seq(xlim.val[1],xlim.val[2],by.x);xmin=seq(xlim.val[1],xlim.val[2],by.x/by.x)
  plot(fit.CY~CY,DP.in.pdat,ylim=ylim.val,xlim=xlim.val,ann=F,axes=F,type="n")
  abline(h=ymaj,v=xmaj,lty=3,col="grey")
  abline(h=0)
  points(m.DP.in$model$CY,partial.resids.DP.in[,2],pch=19,col=inflow.col)
  lines(fit.CY~CY,DP.in.pdat,lwd=2)
  lines(upper.CY ~ CY, data = DP.in.pdat, lty = "dashed")
  lines(lower.CY ~ CY, data = DP.in.pdat, lty = "dashed")
  lines(dsig.CY.incr ~ CY, data = DP.in.pdat, col = "red", lwd = 3,lty=1)
  lines(dsig.CY.decr ~ CY, data = DP.in.pdat, col = "blue", lwd = 3,lty=1)
  axis_fun(1,xmaj,xmin,xmaj,line=-0.5,cex=yaxs.cex);
  axis_fun(2,ymaj,ymin,format(ymaj),cex=yaxs.cex);box(lwd=1)
  mtext(side=3,adj=0,"s(Year)",cex=labs.cex)
  # mtext(side=1,line=2,"Year",cex=labs.cex)
  mtext(side=2,line=1.5,"Effect",cex=labs.cex)
  
  ylim.val=c(1,500);ymaj=log.scale.fun(ylim.val,"major");ymin=log.scale.fun(ylim.val,"minor");#by.y=500;ymaj=seq(ylim.val[1],ylim.val[2],by.y);ymin=seq(ylim.val[1],ylim.val[2],by.y/2)
  xlim.val=date.fun(c("2008-12-01","2020-12-31"));xmaj=seq(xlim.val[1],xlim.val[2],"5 years");xmin=seq(xlim.val[1],xlim.val[2],"1 years")
  plot(DP.ugL~Date,dat.in,ylim=ylim.val,xlim=xlim.val,ann=F,axes=F,type="n",yaxs="i",log="y")
  abline(h=ymaj,v=xmaj,lty=3,col="grey")
  with(dat.in,pt_line(Date,DP.ugL,2,inflow.col,1,21,inflow.col,cex=0.75,pt.col=inflow.col))
  trend=mblm::mblm(value~CY.d,subset(wq.dat.melt,Site=="Godbout"&variable=="DP.ugL"))
  x.val=with(subset(wq.dat.melt,Site=="Godbout"&variable=="DP.ugL"),seq(min(CY.d),max(CY.d),length.out=15))
  fit=predict(trend,newdata=data.frame(CY.d=x.val))
  lines(date.fun(lubridate::date_decimal(x.val)),fit,lwd=2)
  with(subset(pt.trend.all,Site=="Godbout"&param=="DP.ugL"),abline(v=date.fun(lubridate::date_decimal(date.change)),col="red",lty=2))
  axis_fun(1,xmaj,xmin,format(xmaj,"%Y"),line=-0.5,cex=yaxs.cex);
  axis_fun(2,ymaj,ymin,format(round(ymaj/1000,2),digits=2),cex=yaxs.cex);box(lwd=1)
  # mtext(side=1,line=2,"Date",cex=labs.cex)
  mtext(side=2,line=2.5,"DP (mg L\u207B\u00B9)",cex=labs.cex)
  mtext(side=3,adj=0,"Conc.",cex=labs.cex)
  
  ylim.val=c(-2,2);by.y=2;ymaj=seq(ylim.val[1],ylim.val[2],by.y);ymin=seq(ylim.val[1],ylim.val[2],by.y/2)
  xlim.val=c(0,366);by.x=90;xmaj=seq(xlim.val[1],xlim.val[2],by.x);xmin=seq(xlim.val[1],xlim.val[2],by.x/3)
  plot(fit~DOY,DP.out.DOY.sig,ylim=ylim.val,xlim=xlim.val,ann=F,axes=F,type="n")
  abline(h=ymaj,v=xmaj,lty=3,col="grey")
  abline(h=0)
  points(m.DP.out$model$DOY,partial.resids.DP.out[,1],pch=19,col=outflow.col)
  lines(fit~DOY,DP.out.DOY.sig,lwd=2)
  lines(UCI ~ DOY, data = DP.out.DOY.sig, lty = "dashed")
  lines(LCI ~ DOY, data = DP.out.DOY.sig, lty = "dashed")
  lines(dsig.incr ~ DOY, data = DP.out.DOY.sig, col = "red", lwd = 3,lty=1)
  lines(dsig.decre ~ DOY, data = DP.out.DOY.sig, col = "blue", lwd = 3,lty=1)
  axis_fun(1,xmaj,xmin,xmaj,line=-0.5,cex=yaxs.cex);
  axis_fun(2,ymaj,ymin,format(ymaj),cex=yaxs.cex);box(lwd=1)
  mtext(side=3,adj=0,"s(DOY)",cex=labs.cex)
  # mtext(side=1,line=2,"DOY",cex=labs.cex)
  mtext(side=2,line=1.5,"Effect",cex=labs.cex)
  
  ylim.val=c(-2,2);by.y=2;ymaj=seq(ylim.val[1],ylim.val[2],by.y);ymin=seq(ylim.val[1],ylim.val[2],by.y/2)
  xlim.val=c(2010,2020);by.x=5;xmaj=seq(xlim.val[1],xlim.val[2],by.x);xmin=seq(xlim.val[1],xlim.val[2],by.x/by.x)
  plot(fit.CY~CY,DP.out.pdat,ylim=ylim.val,xlim=xlim.val,ann=F,axes=F,type="n")
  abline(h=ymaj,v=xmaj,lty=3,col="grey")
  abline(h=0)
  points(m.DP.out$model$CY,partial.resids.DP.out[,2],pch=19,col=outflow.col)
  lines(fit.CY~CY,DP.out.pdat,lwd=2)
  lines(upper.CY ~ CY, data = DP.out.pdat, lty = "dashed")
  lines(lower.CY ~ CY, data = DP.out.pdat, lty = "dashed")
  lines(dsig.CY.incr ~ CY, data = DP.out.pdat, col = "red", lwd = 3,lty=1)
  lines(dsig.CY.decr ~ CY, data = DP.out.pdat, col = "blue", lwd = 3,lty=1)
  axis_fun(1,xmaj,xmin,xmaj,line=-0.5,cex=yaxs.cex);
  axis_fun(2,ymaj,ymin,format(ymaj),cex=yaxs.cex);box(lwd=1)
  mtext(side=3,adj=0,"s(Year)",cex=labs.cex)
  # mtext(side=1,line=2,"Year",cex=labs.cex)
  # mtext(side=3,line=1,"Outflow",cex=1,font=2)
  mtext(side=2,line=1.5,"Effect",cex=labs.cex)
  
  ylim.val=c(1,500);ymaj=log.scale.fun(ylim.val,"major");ymin=log.scale.fun(ylim.val,"minor");#by.y=500;ymaj=seq(ylim.val[1],ylim.val[2],by.y);ymin=seq(ylim.val[1],ylim.val[2],by.y/2)
  xlim.val=date.fun(c("2008-12-01","2020-12-31"));xmaj=seq(xlim.val[1],xlim.val[2],"5 years");xmin=seq(xlim.val[1],xlim.val[2],"1 years")
  plot(DP.ugL~Date,dat.in,ylim=ylim.val,xlim=xlim.val,ann=F,axes=F,type="n",yaxs="i",log="y")
  abline(h=ymaj,v=xmaj,lty=3,col="grey")
  with(dat.in,pt_line(Date,DP.ugL,2,outflow.col,1,21,outflow.col,cex=0.75,pt.col=outflow.col))
  trend=mblm::mblm(value~CY.d,subset(wq.dat.melt,Site=="Godbout"&variable=="DP.ugL"))
  x.val=with(subset(dat.in,is.na(DP.ugL)==F),seq(min(CY.d),max(CY.d),length.out=15))
  fit=predict(trend,newdata=data.frame(CY.d=x.val))
  lines(date.fun(lubridate::date_decimal(x.val)),fit,lwd=2)
  with(subset(pt.trend.all,Site=="Lake_Outlet"&param=="DP.ugL"),abline(v=date.fun(lubridate::date_decimal(date.change)),col="red",lty=2))
  axis_fun(1,xmaj,xmin,format(xmaj,"%Y"),line=-0.5,cex=yaxs.cex);
  axis_fun(2,ymaj,ymin,format(round(ymaj/1000,2),digits=2),cex=yaxs.cex);box(lwd=1)
  # mtext(side=1,line=2,"Date",cex=labs.cex)
  mtext(side=2,line=2.5,"DP (mg L\u207B\u00B9)",cex=labs.cex)
  mtext(side=3,adj=0,"Conc.",cex=labs.cex)
}

# SRP
{
  ylim.val=c(-2,3);by.y=2;ymaj=seq(ylim.val[1],ylim.val[2],by.y);ymin=seq(ylim.val[1],ylim.val[2],by.y/2)
  xlim.val=c(0,366);by.x=90;xmaj=seq(xlim.val[1],xlim.val[2],by.x);xmin=seq(xlim.val[1],xlim.val[2],by.x/3)
  plot(fit~DOY,SRP.in.DOY.sig,ylim=ylim.val,xlim=xlim.val,ann=F,axes=F,type="n")
  abline(h=ymaj,v=xmaj,lty=3,col="grey")
  abline(h=0)
  points(m.SRP.in$model$DOY,partial.resids.SRP.in[,1],pch=19,col=inflow.col)
  lines(fit~DOY,SRP.in.DOY.sig,lwd=2)
  lines(UCI ~ DOY, data = SRP.in.DOY.sig, lty = "dashed")
  lines(LCI ~ DOY, data = SRP.in.DOY.sig, lty = "dashed")
  lines(dsig.incr ~ DOY, data = SRP.in.DOY.sig, col = "red", lwd = 3,lty=1)
  lines(dsig.decre ~ DOY, data = SRP.in.DOY.sig, col = "blue", lwd = 3,lty=1)
  axis_fun(1,xmaj,xmin,xmaj,line=-0.5,cex=yaxs.cex);
  axis_fun(2,ymaj,ymin,format(ymaj),cex=yaxs.cex);box(lwd=1)
  mtext(side=3,adj=0,"s(DOY)",cex=labs.cex)
  # mtext(side=1,line=2,"DOY",cex=labs.cex)
  mtext(side=2,line=1.5,"Effect",cex=labs.cex)
  
  ylim.val=c(-4,3);by.y=2;ymaj=seq(ylim.val[1],ylim.val[2],by.y);ymin=seq(ylim.val[1],ylim.val[2],by.y/2)
  xlim.val=c(2010,2020);by.x=5;xmaj=seq(xlim.val[1],xlim.val[2],by.x);xmin=seq(xlim.val[1],xlim.val[2],by.x/by.x)
  plot(fit.CY~CY,SRP.in.pdat,ylim=ylim.val,xlim=xlim.val,ann=F,axes=F,type="n")
  abline(h=ymaj,v=xmaj,lty=3,col="grey")
  abline(h=0)
  points(m.SRP.in$model$CY,partial.resids.SRP.in[,2],pch=19,col=inflow.col)
  lines(fit.CY~CY,SRP.in.pdat,lwd=2)
  lines(upper.CY ~ CY, data = SRP.in.pdat, lty = "dashed")
  lines(lower.CY ~ CY, data = SRP.in.pdat, lty = "dashed")
  lines(dsig.CY.incr ~ CY, data = SRP.in.pdat, col = "red", lwd = 3,lty=1)
  lines(dsig.CY.decr ~ CY, data = SRP.in.pdat, col = "blue", lwd = 3,lty=1)
  axis_fun(1,xmaj,xmin,xmaj,line=-0.5,cex=yaxs.cex);
  axis_fun(2,ymaj,ymin,format(ymaj),cex=yaxs.cex);box(lwd=1)
  mtext(side=3,adj=0,"s(Year)",cex=labs.cex)
  # mtext(side=1,line=2,"Year",cex=labs.cex)
  mtext(side=2,line=1.5,"Effect",cex=labs.cex)
  
  ylim.val=c(1,500);ymaj=log.scale.fun(ylim.val,"major");ymin=log.scale.fun(ylim.val,"minor");#by.y=500;ymaj=seq(ylim.val[1],ylim.val[2],by.y);ymin=seq(ylim.val[1],ylim.val[2],by.y/2)
  xlim.val=date.fun(c("2008-12-01","2020-12-31"));xmaj=seq(xlim.val[1],xlim.val[2],"5 years");xmin=seq(xlim.val[1],xlim.val[2],"1 years")
  plot(SRP.ugL~Date,dat.in,ylim=ylim.val,xlim=xlim.val,ann=F,axes=F,type="n",yaxs="i",log="y")
  abline(h=ymaj,v=xmaj,lty=3,col="grey")
  with(dat.in,pt_line(Date,SRP.ugL,2,inflow.col,1,21,inflow.col,cex=0.75,pt.col=inflow.col))
  trend=mblm::mblm(value~CY.d,subset(wq.dat.melt,Site=="Godbout"&variable=="SRP.ugL"))
  x.val=with(subset(wq.dat.melt,Site=="Godbout"&variable=="SRP.ugL"),seq(min(CY.d),max(CY.d),length.out=15))
  fit=predict(trend,newdata=data.frame(CY.d=x.val))
  lines(date.fun(lubridate::date_decimal(x.val)),fit,lwd=2)
  with(subset(pt.trend.all,Site=="Godbout"&param=="SRP.ugL"),abline(v=date.fun(lubridate::date_decimal(date.change)),col="red",lty=2))
  axis_fun(1,xmaj,xmin,format(xmaj,"%Y"),line=-0.5,cex=yaxs.cex);
  axis_fun(2,ymaj,ymin,format(round(ymaj/1000,2),digits=2),cex=yaxs.cex);box(lwd=1)
  # mtext(side=1,line=2,"Date",cex=labs.cex)
  mtext(side=2,line=2.5,"SRP (mg L\u207B\u00B9)",cex=labs.cex)
  mtext(side=3,adj=0,"Conc.",cex=labs.cex)
  
  ylim.val=c(-3,3);by.y=3;ymaj=seq(ylim.val[1],ylim.val[2],by.y);ymin=seq(ylim.val[1],ylim.val[2],by.y/2)
  xlim.val=c(0,366);by.x=90;xmaj=seq(xlim.val[1],xlim.val[2],by.x);xmin=seq(xlim.val[1],xlim.val[2],by.x/3)
  plot(fit~DOY,SRP.out.DOY.sig,ylim=ylim.val,xlim=xlim.val,ann=F,axes=F,type="n")
  abline(h=ymaj,v=xmaj,lty=3,col="grey")
  abline(h=0)
  points(m.SRP.out$model$DOY,partial.resids.SRP.out[,1],pch=19,col=outflow.col)
  lines(fit~DOY,SRP.out.DOY.sig,lwd=2)
  lines(UCI ~ DOY, data = SRP.out.DOY.sig, lty = "dashed")
  lines(LCI ~ DOY, data = SRP.out.DOY.sig, lty = "dashed")
  lines(dsig.incr ~ DOY, data = SRP.out.DOY.sig, col = "red", lwd = 3,lty=1)
  lines(dsig.decre ~ DOY, data = SRP.out.DOY.sig, col = "blue", lwd = 3,lty=1)
  axis_fun(1,xmaj,xmin,xmaj,line=-0.5,cex=yaxs.cex);
  axis_fun(2,ymaj,ymin,format(ymaj),cex=yaxs.cex);box(lwd=1)
  mtext(side=3,adj=0,"s(DOY)",cex=labs.cex)
  # mtext(side=1,line=2,"DOY",cex=labs.cex)
  mtext(side=2,line=1.5,"Effect",cex=labs.cex)
  
  ylim.val=c(-2,2);by.y=2;ymaj=seq(ylim.val[1],ylim.val[2],by.y);ymin=seq(ylim.val[1],ylim.val[2],by.y/2)
  xlim.val=c(2010,2020);by.x=5;xmaj=seq(xlim.val[1],xlim.val[2],by.x);xmin=seq(xlim.val[1],xlim.val[2],by.x/by.x)
  plot(fit.CY~CY,SRP.out.pdat,ylim=ylim.val,xlim=xlim.val,ann=F,axes=F,type="n")
  abline(h=ymaj,v=xmaj,lty=3,col="grey")
  abline(h=0)
  points(m.SRP.out$model$CY,partial.resids.SRP.out[,2],pch=19,col=outflow.col)
  lines(fit.CY~CY,SRP.out.pdat,lwd=2)
  lines(upper.CY ~ CY, data = SRP.out.pdat, lty = "dashed")
  lines(lower.CY ~ CY, data = SRP.out.pdat, lty = "dashed")
  lines(dsig.CY.incr ~ CY, data = SRP.out.pdat, col = "red", lwd = 3,lty=1)
  lines(dsig.CY.decr ~ CY, data = SRP.out.pdat, col = "blue", lwd = 3,lty=1)
  axis_fun(1,xmaj,xmin,xmaj,line=-0.5,cex=yaxs.cex);
  axis_fun(2,ymaj,ymin,format(ymaj),cex=yaxs.cex);box(lwd=1)
  mtext(side=3,adj=0,"s(Year)",cex=labs.cex)
  # mtext(side=1,line=2,"Year",cex=labs.cex)
  # mtext(side=3,line=1,"Outflow",cex=1,font=2)
  mtext(side=2,line=1.5,"Effect",cex=labs.cex)
  
  ylim.val=c(1,500);ymaj=log.scale.fun(ylim.val,"major");ymin=log.scale.fun(ylim.val,"minor");#by.y=500;ymaj=seq(ylim.val[1],ylim.val[2],by.y);ymin=seq(ylim.val[1],ylim.val[2],by.y/2)
  xlim.val=date.fun(c("2008-12-01","2020-12-31"));xmaj=seq(xlim.val[1],xlim.val[2],"5 years");xmin=seq(xlim.val[1],xlim.val[2],"1 years")
  plot(SRP.ugL~Date,dat.in,ylim=ylim.val,xlim=xlim.val,ann=F,axes=F,type="n",yaxs="i",log="y")
  abline(h=ymaj,v=xmaj,lty=3,col="grey")
  with(dat.in,pt_line(Date,SRP.ugL,2,outflow.col,1,21,outflow.col,cex=0.75,pt.col=outflow.col))
  trend=mblm::mblm(value~CY.d,subset(wq.dat.melt,Site=="Godbout"&variable=="SRP.ugL"))
  x.val=with(subset(dat.in,is.na(SRP.ugL)==F),seq(min(CY.d),max(CY.d),length.out=15))
  fit=predict(trend,newdata=data.frame(CY.d=x.val))
  lines(date.fun(lubridate::date_decimal(x.val)),fit,lwd=2)
  with(subset(pt.trend.all,Site=="Lake_Outlet"&param=="SRP.ugL"),abline(v=date.fun(lubridate::date_decimal(date.change)),col="red",lty=2))
  axis_fun(1,xmaj,xmin,format(xmaj,"%Y"),line=-0.5,cex=yaxs.cex);
  axis_fun(2,ymaj,ymin,format(round(ymaj/1000,2),digits=2),cex=yaxs.cex);box(lwd=1)
  # mtext(side=1,line=2,"Date",cex=labs.cex)
  mtext(side=2,line=2.5,"SRP (mg L\u207B\u00B9)",cex=labs.cex)
  mtext(side=3,adj=0,"Conc.",cex=labs.cex)
}

# PP
{
  ylim.val=c(-3,4);by.y=3;ymaj=seq(ylim.val[1],ylim.val[2],by.y);ymin=seq(ylim.val[1],ylim.val[2],by.y/2)
  xlim.val=c(0,366);by.x=90;xmaj=seq(xlim.val[1],xlim.val[2],by.x);xmin=seq(xlim.val[1],xlim.val[2],by.x/3)
  plot(fit~DOY,PP.in.DOY.sig,ylim=ylim.val,xlim=xlim.val,ann=F,axes=F,type="n")
  abline(h=ymaj,v=xmaj,lty=3,col="grey")
  abline(h=0)
  points(m.PP.in$model$DOY,partial.resids.PP.in[,1],pch=19,col=inflow.col)
  lines(fit~DOY,PP.in.DOY.sig,lwd=2)
  lines(UCI ~ DOY, data = PP.in.DOY.sig, lty = "dashed")
  lines(LCI ~ DOY, data = PP.in.DOY.sig, lty = "dashed")
  lines(dsig.incr ~ DOY, data = PP.in.DOY.sig, col = "red", lwd = 3,lty=1)
  lines(dsig.decre ~ DOY, data = PP.in.DOY.sig, col = "blue", lwd = 3,lty=1)
  axis_fun(1,xmaj,xmin,xmaj,line=-0.5,cex=yaxs.cex);
  axis_fun(2,ymaj,ymin,format(ymaj),cex=yaxs.cex);box(lwd=1)
  mtext(side=3,adj=0,"s(DOY)",cex=labs.cex)
  # mtext(side=1,line=2,"DOY",cex=labs.cex)
  mtext(side=2,line=1.5,"Effect",cex=labs.cex)
  
  ylim.val=c(-3,4);by.y=3;ymaj=seq(ylim.val[1],ylim.val[2],by.y);ymin=seq(ylim.val[1],ylim.val[2],by.y/2)
  xlim.val=c(2010,2020);by.x=5;xmaj=seq(xlim.val[1],xlim.val[2],by.x);xmin=seq(xlim.val[1],xlim.val[2],by.x/by.x)
  plot(fit.CY~CY,PP.in.pdat,ylim=ylim.val,xlim=xlim.val,ann=F,axes=F,type="n")
  abline(h=ymaj,v=xmaj,lty=3,col="grey")
  abline(h=0)
  points(m.PP.in$model$CY,partial.resids.PP.in[,2],pch=19,col=inflow.col)
  lines(fit.CY~CY,PP.in.pdat,lwd=2)
  lines(upper.CY ~ CY, data = PP.in.pdat, lty = "dashed")
  lines(lower.CY ~ CY, data = PP.in.pdat, lty = "dashed")
  lines(dsig.CY.incr ~ CY, data = PP.in.pdat, col = "red", lwd = 3,lty=1)
  lines(dsig.CY.decr ~ CY, data = PP.in.pdat, col = "blue", lwd = 3,lty=1)
  axis_fun(1,xmaj,xmin,xmaj,line=-0.5,cex=yaxs.cex);
  axis_fun(2,ymaj,ymin,format(ymaj),cex=yaxs.cex);box(lwd=1)
  mtext(side=3,adj=0,"s(Year)",cex=labs.cex)
  # mtext(side=1,line=2,"Year",cex=labs.cex)
  mtext(side=2,line=1.5,"Effect",cex=labs.cex)
  
  ylim.val=c(1,500);ymaj=log.scale.fun(ylim.val,"major");ymin=log.scale.fun(ylim.val,"minor");#by.y=500;ymaj=seq(ylim.val[1],ylim.val[2],by.y);ymin=seq(ylim.val[1],ylim.val[2],by.y/2)
  xlim.val=date.fun(c("2008-12-01","2020-12-31"));xmaj=seq(xlim.val[1],xlim.val[2],"5 years");xmin=seq(xlim.val[1],xlim.val[2],"1 years")
  plot(PP.ugL~Date,dat.in,ylim=ylim.val,xlim=xlim.val,ann=F,axes=F,type="n",yaxs="i",log="y")
  abline(h=ymaj,v=xmaj,lty=3,col="grey")
  with(dat.in,pt_line(Date,PP.ugL,2,inflow.col,1,21,inflow.col,cex=0.75,pt.col=inflow.col))
  trend=mblm::mblm(value~CY.d,subset(wq.dat.melt,Site=="Godbout"&variable=="PP.ugL"))
  x.val=with(subset(wq.dat.melt,Site=="Godbout"&variable=="PP.ugL"),seq(min(CY.d),max(CY.d),length.out=15))
  fit=predict(trend,newdata=data.frame(CY.d=x.val))
  lines(date.fun(lubridate::date_decimal(x.val)),fit,lwd=2)
  with(subset(pt.trend.all,Site=="Godbout"&param=="PP.ugL"),abline(v=date.fun(lubridate::date_decimal(date.change)),col="red",lty=2))
  axis_fun(1,xmaj,xmin,format(xmaj,"%Y"),line=-0.5,cex=yaxs.cex);
  axis_fun(2,ymaj,ymin,format(round(ymaj/1000,2),digits=2),cex=yaxs.cex);box(lwd=1)
  # mtext(side=1,line=2,"Date",cex=labs.cex)
  mtext(side=2,line=2.5,"PP (mg L\u207B\u00B9)",cex=labs.cex)
  mtext(side=3,adj=0,"Conc.",cex=labs.cex)
  
  ylim.val=c(-4,4);by.y=4;ymaj=seq(ylim.val[1],ylim.val[2],by.y);ymin=seq(ylim.val[1],ylim.val[2],by.y/2)
  xlim.val=c(0,366);by.x=90;xmaj=seq(xlim.val[1],xlim.val[2],by.x);xmin=seq(xlim.val[1],xlim.val[2],by.x/3)
  plot(fit~DOY,PP.out.DOY.sig,ylim=ylim.val,xlim=xlim.val,ann=F,axes=F,type="n")
  abline(h=ymaj,v=xmaj,lty=3,col="grey")
  abline(h=0)
  points(m.PP.out$model$DOY,partial.resids.PP.out[,1],pch=19,col=outflow.col)
  lines(fit~DOY,PP.out.DOY.sig,lwd=2)
  lines(UCI ~ DOY, data = PP.out.DOY.sig, lty = "dashed")
  lines(LCI ~ DOY, data = PP.out.DOY.sig, lty = "dashed")
  lines(dsig.incr ~ DOY, data = PP.out.DOY.sig, col = "red", lwd = 3,lty=1)
  lines(dsig.decre ~ DOY, data = PP.out.DOY.sig, col = "blue", lwd = 3,lty=1)
  axis_fun(1,xmaj,xmin,xmaj,line=-0.5,cex=yaxs.cex);
  axis_fun(2,ymaj,ymin,format(ymaj),cex=yaxs.cex);box(lwd=1)
  mtext(side=3,adj=0,"s(DOY)",cex=labs.cex)
  # mtext(side=1,line=2,"DOY",cex=labs.cex)
  mtext(side=2,line=1.5,"Effect",cex=labs.cex)
  
  ylim.val=c(-5,2);by.y=5;ymaj=seq(ylim.val[1],ylim.val[2],by.y);ymin=seq(ylim.val[1],ylim.val[2],by.y/2)
  xlim.val=c(2010,2020);by.x=5;xmaj=seq(xlim.val[1],xlim.val[2],by.x);xmin=seq(xlim.val[1],xlim.val[2],by.x/by.x)
  plot(fit.CY~CY,PP.out.pdat,ylim=ylim.val,xlim=xlim.val,ann=F,axes=F,type="n")
  abline(h=ymaj,v=xmaj,lty=3,col="grey")
  abline(h=0)
  points(m.PP.out$model$CY,partial.resids.PP.out[,2],pch=19,col=outflow.col)
  lines(fit.CY~CY,PP.out.pdat,lwd=2)
  lines(upper.CY ~ CY, data = PP.out.pdat, lty = "dashed")
  lines(lower.CY ~ CY, data = PP.out.pdat, lty = "dashed")
  lines(dsig.CY.incr ~ CY, data = PP.out.pdat, col = "red", lwd = 3,lty=1)
  lines(dsig.CY.decr ~ CY, data = PP.out.pdat, col = "blue", lwd = 3,lty=1)
  axis_fun(1,xmaj,xmin,xmaj,line=-0.5,cex=yaxs.cex);
  axis_fun(2,ymaj,ymin,format(ymaj),cex=yaxs.cex);box(lwd=1)
  mtext(side=3,adj=0,"s(Year)",cex=labs.cex)
  # mtext(side=1,line=2,"Year",cex=labs.cex)
  # mtext(side=3,line=1,"Outflow",cex=1,font=2)
  mtext(side=2,line=1.5,"Effect",cex=labs.cex)
  
  ylim.val=c(1,500);ymaj=log.scale.fun(ylim.val,"major");ymin=log.scale.fun(ylim.val,"minor");#by.y=500;ymaj=seq(ylim.val[1],ylim.val[2],by.y);ymin=seq(ylim.val[1],ylim.val[2],by.y/2)
  xlim.val=date.fun(c("2008-12-01","2020-12-31"));xmaj=seq(xlim.val[1],xlim.val[2],"5 years");xmin=seq(xlim.val[1],xlim.val[2],"1 years")
  plot(PP.ugL~Date,dat.in,ylim=ylim.val,xlim=xlim.val,ann=F,axes=F,type="n",yaxs="i",log="y")
  abline(h=ymaj,v=xmaj,lty=3,col="grey")
  with(dat.in,pt_line(Date,PP.ugL,2,outflow.col,1,21,outflow.col,cex=0.75,pt.col=outflow.col))
  trend=mblm::mblm(value~CY.d,subset(wq.dat.melt,Site=="Godbout"&variable=="PP.ugL"))
  x.val=with(subset(dat.in,is.na(PP.ugL)==F),seq(min(CY.d),max(CY.d),length.out=15))
  fit=predict(trend,newdata=data.frame(CY.d=x.val))
  lines(date.fun(lubridate::date_decimal(x.val)),fit,lwd=2)
  with(subset(pt.trend.all,Site=="Lake_Outlet"&param=="PP.ugL"),abline(v=date.fun(lubridate::date_decimal(date.change)),col="red",lty=2))
  axis_fun(1,xmaj,xmin,format(xmaj,"%Y"),line=-0.5,cex=yaxs.cex);
  axis_fun(2,ymaj,ymin,format(round(ymaj/1000,2),digits=2),cex=yaxs.cex);box(lwd=1)
  # mtext(side=1,line=2,"Date",cex=labs.cex)
  mtext(side=2,line=2.5,"PP (mg L\u207B\u00B9)",cex=labs.cex)
  mtext(side=3,adj=0,"Conc.",cex=labs.cex)
}

# DOP
{
  ylim.val=c(-3,2);by.y=3;ymaj=seq(ylim.val[1],ylim.val[2],by.y);ymin=seq(ylim.val[1],ylim.val[2],by.y/2)
  xlim.val=c(0,366);by.x=90;xmaj=seq(xlim.val[1],xlim.val[2],by.x);xmin=seq(xlim.val[1],xlim.val[2],by.x/3)
  plot(fit~DOY,DOP.in.DOY.sig,ylim=ylim.val,xlim=xlim.val,ann=F,axes=F,type="n")
  abline(h=ymaj,v=xmaj,lty=3,col="grey")
  abline(h=0)
  points(m.DOP.in$model$DOY,partial.resids.DOP.in[,1],pch=19,col=inflow.col)
  lines(fit~DOY,DOP.in.DOY.sig,lwd=2)
  lines(UCI ~ DOY, data = DOP.in.DOY.sig, lty = "dashed")
  lines(LCI ~ DOY, data = DOP.in.DOY.sig, lty = "dashed")
  lines(dsig.incr ~ DOY, data = DOP.in.DOY.sig, col = "red", lwd = 3,lty=1)
  lines(dsig.decre ~ DOY, data = DOP.in.DOY.sig, col = "blue", lwd = 3,lty=1)
  axis_fun(1,xmaj,xmin,xmaj,line=-0.5,cex=yaxs.cex);
  axis_fun(2,ymaj,ymin,format(ymaj),cex=yaxs.cex);box(lwd=1)
  mtext(side=3,adj=0,"s(DOY)",cex=labs.cex)
  mtext(side=1,line=2,"DOY",cex=labs.cex)
  mtext(side=2,line=1.5,"Effect",cex=labs.cex)
  
  ylim.val=c(-3,3);by.y=3;ymaj=seq(ylim.val[1],ylim.val[2],by.y);ymin=seq(ylim.val[1],ylim.val[2],by.y/2)
  xlim.val=c(2010,2020);by.x=5;xmaj=seq(xlim.val[1],xlim.val[2],by.x);xmin=seq(xlim.val[1],xlim.val[2],by.x/by.x)
  plot(fit.CY~CY,DOP.in.pdat,ylim=ylim.val,xlim=xlim.val,ann=F,axes=F,type="n")
  abline(h=ymaj,v=xmaj,lty=3,col="grey")
  abline(h=0)
  points(m.DOP.in$model$CY,partial.resids.DOP.in[,2],pch=19,col=inflow.col)
  lines(fit.CY~CY,DOP.in.pdat,lwd=2)
  lines(upper.CY ~ CY, data = DOP.in.pdat, lty = "dashed")
  lines(lower.CY ~ CY, data = DOP.in.pdat, lty = "dashed")
  lines(dsig.CY.incr ~ CY, data = DOP.in.pdat, col = "red", lwd = 3,lty=1)
  lines(dsig.CY.decr ~ CY, data = DOP.in.pdat, col = "blue", lwd = 3,lty=1)
  axis_fun(1,xmaj,xmin,xmaj,line=-0.5,cex=yaxs.cex);
  axis_fun(2,ymaj,ymin,format(ymaj),cex=yaxs.cex);box(lwd=1)
  mtext(side=3,adj=0,"s(Year)",cex=labs.cex)
  mtext(side=1,line=2,"Year",cex=labs.cex)
  mtext(side=2,line=1.5,"Effect",cex=labs.cex)
  
  ylim.val=c(1,500);ymaj=log.scale.fun(ylim.val,"major");ymin=log.scale.fun(ylim.val,"minor");#by.y=500;ymaj=seq(ylim.val[1],ylim.val[2],by.y);ymin=seq(ylim.val[1],ylim.val[2],by.y/2)
  xlim.val=date.fun(c("2008-12-01","2020-12-31"));xmaj=seq(xlim.val[1],xlim.val[2],"5 years");xmin=seq(xlim.val[1],xlim.val[2],"1 years")
  plot(DOP.ugL~Date,dat.in,ylim=ylim.val,xlim=xlim.val,ann=F,axes=F,type="n",yaxs="i",log="y")
  abline(h=ymaj,v=xmaj,lty=3,col="grey")
  with(dat.in,pt_line(Date,DOP.ugL,2,inflow.col,1,21,inflow.col,cex=0.75,pt.col=inflow.col))
  trend=mblm::mblm(value~CY.d,subset(wq.dat.melt,Site=="Godbout"&variable=="DOP.ugL"))
  x.val=with(subset(wq.dat.melt,Site=="Godbout"&variable=="DOP.ugL"),seq(min(CY.d),max(CY.d),length.out=15))
  fit=predict(trend,newdata=data.frame(CY.d=x.val))
  lines(date.fun(lubridate::date_decimal(x.val)),fit,lwd=2)
  with(subset(pt.trend.all,Site=="Godbout"&param=="DOP.ugL"),abline(v=date.fun(lubridate::date_decimal(date.change)),col="red",lty=2))
  axis_fun(1,xmaj,xmin,format(xmaj,"%Y"),line=-0.5,cex=yaxs.cex);
  axis_fun(2,ymaj,ymin,format(round(ymaj/1000,2),digits=2),cex=yaxs.cex);box(lwd=1)
  mtext(side=1,line=2,"Date",cex=labs.cex)
  mtext(side=2,line=2.5,"DOP (mg L\u207B\u00B9)",cex=labs.cex)
  mtext(side=3,adj=0,"Conc.",cex=labs.cex)
  
  ylim.val=c(-3,3);by.y=3;ymaj=seq(ylim.val[1],ylim.val[2],by.y);ymin=seq(ylim.val[1],ylim.val[2],by.y/2)
  xlim.val=c(0,366);by.x=90;xmaj=seq(xlim.val[1],xlim.val[2],by.x);xmin=seq(xlim.val[1],xlim.val[2],by.x/3)
  plot(fit~DOY,DOP.out.DOY.sig,ylim=ylim.val,xlim=xlim.val,ann=F,axes=F,type="n")
  abline(h=ymaj,v=xmaj,lty=3,col="grey")
  abline(h=0)
  points(m.DOP.out$model$DOY,partial.resids.DOP.out[,1],pch=19,col=outflow.col)
  lines(fit~DOY,DOP.out.DOY.sig,lwd=2)
  lines(UCI ~ DOY, data = DOP.out.DOY.sig, lty = "dashed")
  lines(LCI ~ DOY, data = DOP.out.DOY.sig, lty = "dashed")
  lines(dsig.incr ~ DOY, data = DOP.out.DOY.sig, col = "red", lwd = 3,lty=1)
  lines(dsig.decre ~ DOY, data = DOP.out.DOY.sig, col = "blue", lwd = 3,lty=1)
  axis_fun(1,xmaj,xmin,xmaj,line=-0.5,cex=yaxs.cex);
  axis_fun(2,ymaj,ymin,format(ymaj),cex=yaxs.cex);box(lwd=1)
  mtext(side=3,adj=0,"s(DOY)",cex=labs.cex)
  mtext(side=1,line=2,"DOY",cex=labs.cex)
  mtext(side=2,line=1.5,"Effect",cex=labs.cex)
  
  ylim.val=c(-2,2);by.y=2;ymaj=seq(ylim.val[1],ylim.val[2],by.y);ymin=seq(ylim.val[1],ylim.val[2],by.y/2)
  xlim.val=c(2010,2020);by.x=5;xmaj=seq(xlim.val[1],xlim.val[2],by.x);xmin=seq(xlim.val[1],xlim.val[2],by.x/by.x)
  plot(fit.CY~CY,DOP.out.pdat,ylim=ylim.val,xlim=xlim.val,ann=F,axes=F,type="n")
  abline(h=ymaj,v=xmaj,lty=3,col="grey")
  abline(h=0)
  points(m.DOP.out$model$CY,partial.resids.DOP.out[,2],pch=19,col=outflow.col)
  lines(fit.CY~CY,DOP.out.pdat,lwd=2)
  lines(upper.CY ~ CY, data = DOP.out.pdat, lty = "dashed")
  lines(lower.CY ~ CY, data = DOP.out.pdat, lty = "dashed")
  lines(dsig.CY.incr ~ CY, data = DOP.out.pdat, col = "red", lwd = 3,lty=1)
  lines(dsig.CY.decr ~ CY, data = DOP.out.pdat, col = "blue", lwd = 3,lty=1)
  axis_fun(1,xmaj,xmin,xmaj,line=-0.5,cex=yaxs.cex);
  axis_fun(2,ymaj,ymin,format(ymaj),cex=yaxs.cex);box(lwd=1)
  mtext(side=3,adj=0,"s(Year)",cex=labs.cex)
  mtext(side=1,line=2,"Year",cex=labs.cex)
  # mtext(side=3,line=1,"Outflow",cex=1,font=2)
  mtext(side=2,line=1.5,"Effect",cex=labs.cex)
  
  ylim.val=c(1,500);ymaj=log.scale.fun(ylim.val,"major");ymin=log.scale.fun(ylim.val,"minor");#by.y=500;ymaj=seq(ylim.val[1],ylim.val[2],by.y);ymin=seq(ylim.val[1],ylim.val[2],by.y/2)
  xlim.val=date.fun(c("2008-12-01","2020-12-31"));xmaj=seq(xlim.val[1],xlim.val[2],"5 years");xmin=seq(xlim.val[1],xlim.val[2],"1 years")
  plot(DOP.ugL~Date,dat.in,ylim=ylim.val,xlim=xlim.val,ann=F,axes=F,type="n",yaxs="i",log="y")
  abline(h=ymaj,v=xmaj,lty=3,col="grey")
  with(dat.in,pt_line(Date,DOP.ugL,2,outflow.col,1,21,outflow.col,cex=0.75,pt.col=outflow.col))
  trend=mblm::mblm(value~CY.d,subset(wq.dat.melt,Site=="Godbout"&variable=="DOP.ugL"))
  x.val=with(subset(dat.in,is.na(DOP.ugL)==F),seq(min(CY.d),max(CY.d),length.out=15))
  fit=predict(trend,newdata=data.frame(CY.d=x.val))
  lines(date.fun(lubridate::date_decimal(x.val)),fit,lwd=2)
  with(subset(pt.trend.all,Site=="Lake_Outlet"&param=="DOP.ugL"),abline(v=date.fun(lubridate::date_decimal(date.change)),col="red",lty=2))
  axis_fun(1,xmaj,xmin,format(xmaj,"%Y"),line=-0.5,cex=yaxs.cex);
  axis_fun(2,ymaj,ymin,format(round(ymaj/1000,2),digits=2),cex=yaxs.cex);box(lwd=1)
  mtext(side=1,line=2,"Date",cex=labs.cex)
  mtext(side=2,line=2.5,"DOP (mg L\u207B\u00B9)",cex=labs.cex)
  mtext(side=3,adj=0,"Conc.",cex=labs.cex)
}

dev.off()